# Generated by Django 2.2.1 on 2019-05-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
