# Generated by Django 2.2.1 on 2019-06-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='skills_required',
        ),
    ]
