# Generated by Django 2.2.2 on 2019-06-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='zipfile',
            new_name='file',
        ),
    ]
