# Generated by Django 2.2.1 on 2019-06-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_assignment_skills_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='skills',
            new_name='skills_required',
        ),
    ]
