# Generated by Django 2.2.1 on 2019-05-30 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190530_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='project_data',
        ),
    ]
