# Generated by Django 2.2.1 on 2019-05-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_assignment_project_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='completed',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='is_assigned',
            field=models.CharField(default='', max_length=50),
        ),
    ]
