# Generated by Django 2.2.1 on 2019-06-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190603_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
